# Generated by Django 6.0 on 2025-12-24 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCareProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('img_url', models.ImageField(upload_to='uploads/')),
                ('cv', models.FileField(upload_to='pdf/')),
                ('license_count', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_type', models.CharField(max_length=200)),
                ('cancer_treatment_type', models.CharField(max_length=400)),
                ('medicine_and_dose', models.CharField(max_length=300)),
                ('chemo_history_count', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_of_birth', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareGiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver', to='users.patient')),
            ],
        ),
    ]
