# Generated by Django 6.0 on 2025-12-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_healthcareprovider_patient_caregiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
