# Generated by Django 6.0.1 on 2026-01-25 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_first_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_type', models.CharField(max_length=200)),
                ('cancer_treatment_type', models.CharField(max_length=400)),
                ('medicine_and_dose', models.CharField(max_length=300)),
                ('chemo_history_count', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_of_birth', models.DateField()),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cancer_treatment_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cancer_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='chemo_history_count',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medicine_and_dose',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='region',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight',
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.medicalprofile'),
            preserve_default=False,
        ),
    ]
