# Generated by Django 6.0.1 on 2026-01-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_medicalprofile_remove_caregiver_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PATIENT', 'Patient'), ('CAREGIVER', 'Caregiver'), ('hEALTHCARE', 'Healthcare')], default='PATIENT', max_length=20),
        ),
    ]
