# Generated by Django 6.0.1 on 2026-01-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='cancer_treatment_type',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='cancer_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='chemo_history_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='medicine_and_dose',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PATIENT', 'Patient'), ('CAREGIVER', 'Caregiver'), ('HEALTHCARE', 'Healthcare')], default='PATIENT', max_length=20),
        ),
    ]
