# Generated by Django 6.0.1 on 2026-01-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_medicalprofile_cancer_treatment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
