# Generated by Django 6.0.1 on 2026-01-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_medicalprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_Onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
