# Generated by Django 6.0.1 on 2026-01-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='chemo_history_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
