# Generated by Django 6.0.1 on 2026-01-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_medicalprofile_chemo_history_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
