# Generated by Django 6.0.1 on 2026-03-10 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_registrationqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caregivers', to='users.patient'),
            preserve_default=False,
        ),
    ]
