# Generated by Django 6.0.1 on 2026-03-10 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_caregiver_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='relationship',
        ),
        migrations.CreateModel(
            name='CaregiverPatientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('can_book_appointment', models.BooleanField(default=True)),
                ('can_view_medical_records', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relations', to='users.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_relations', to='users.patient')),
            ],
            options={
                'unique_together': {('patient', 'caregiver')},
            },
        ),
    ]
