# Generated by Django 6.0.1 on 2026-03-11 03:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_caregiver_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverpatientrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('wife', 'Wife'), ('husband', 'Husband'), ('friend', 'Friend'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='caregiverpatientrelationship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CaregiverVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('relationship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.caregiverpatientrelationship')),
            ],
        ),
    ]
