# Generated by Django 6.0.1 on 2026-03-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiververification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
