# Generated by Django 6.0.1 on 2026-04-13 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_weighthistory_bmi_alter_weighthistory_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.medicalprofile'),
        ),
    ]
