# Generated by Django 6.0.1 on 2026-04-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_patient_medical_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
