# Generated by Django 6.0.1 on 2026-04-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_medicalprofile_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprovider',
            name='patient_count',
            field=models.IntegerField(default=0),
        ),
    ]
