# Generated by Django 6.0.1 on 2026-05-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_healthcareprovider_patient_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiververification',
            name='expires_at',
        ),
    ]
