# Generated by Django 6.0.1 on 2026-04-03 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityslot',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2026, 4, 3, 19, 23, 19, 197336, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='consume_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='max_visit_patient',
            field=models.IntegerField(default=0),
        ),
    ]
