# Generated by Django 6.0.1 on 2026-04-13 18:25

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_availabilityslot_appointment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='scheduled',
            new_name='appointment_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2026, 4, 13, 18, 22, 39, 343336, tzinfo=datetime.timezone.utc)),
        ),
    ]
