# Generated by Django 6.0.1 on 2026-04-13 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityslot',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2026, 4, 13, 18, 28, 1, 667253, tzinfo=datetime.timezone.utc)),
        ),
    ]
