# Generated by Django 6.0.1 on 2026-05-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_remove_appointment_slot_remove_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='doctorworkingday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorworkingday',
            name='days',
            field=models.ManyToManyField(related_name='doctors', to='appointment.day'),
        ),
        migrations.RemoveField(
            model_name='doctorworkingday',
            name='day_of_week',
        ),
    ]
