# Generated by Django 6.0.1 on 2026-05-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_doctoravailability_doctorslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorworkingday',
            name='days',
        ),
        migrations.RemoveField(
            model_name='doctorworkingday',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
        migrations.DeleteModel(
            name='DoctorWorkingDay',
        ),
    ]
