# Generated by Django 6.0.1 on 2026-05-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_remove_doctorworkingday_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
