# Generated by Django 6.0.1 on 2026-05-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_appointment_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
    ]
