# Generated by Django 6.0.1 on 2026-05-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_remove_appointment_appointment_time'),
        ('users', '0024_healthcareprovider_patient_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_appointments', to='users.caregiver'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_appointments', to='users.healthcareprovider'),
        ),
    ]
