# Generated by Django 6.0.1 on 2026-05-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_timeslot_remove_doctorslot_availability_and_more'),
        ('users', '0024_healthcareprovider_patient_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailable',
            unique_together={('doctor', 'day', 'time_slot')},
        ),
    ]
