# Generated by Django 6.0.1 on 2026-05-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_alter_appointment_slot'),
        ('users', '0024_healthcareprovider_patient_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('provider', 'slot', 'appointment_date')},
        ),
    ]
