# Generated by Django 6.0.1 on 2026-05-16 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_alter_appointment_options_and_more'),
        ('users', '0024_healthcareprovider_patient_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='users.patient'),
        ),
    ]
