# Generated by Django 6.0.1 on 2026-01-30 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_weighthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medicalFile/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('prescription', 'Prescription'), ('lab_report', 'Lab Report'), ('xray', 'X-Ray'), ('mri', 'MRI'), ('discharge', 'Discharge Summary'), ('other', 'Other')], default='prescription', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicalFile', to='users.patient')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
