# Generated by Django 6.0.1 on 2026-01-30 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        ('users', '0013_weighthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalfile',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_files', to='users.patient'),
        ),
    ]
